
result_root: /home/longshen/data/results
out_dir: mjn_5pfm/instcls/from_mix_guitar_segment

train:
  n_epoch: 10
  lr: 0.0001
  mert_lr: 0.00001
  weight_decay: 0
  warmup_steps: 0
  val_check_interval: 0.2 # Validate every X epoch
  lr_anneal_patience: 5 # 3
  earlystop_patience: 10

model:
  lit_model: LitMertSoloGuitar
  model_class: MertSoloDetectorFromMixSegment
  mert_url: /home/longshen/data/mert # m-a-p/MERT-v1-95M
  ckpt_fp: /data2/longshen/lead_inst_detect_data/data/results_test/lead_inst_track_mjn/checkpoints/segment_guitar_cls_mjn.ckpt
  num_inst_type: 2 # 14 inst + 1 na + 0 reserved for padding
  mix_ch_id: 10
  freeze_mert: False

dataset:
  data_root: /home/longshen/data/datasets/MJN/segmented/5perfs
  dataset_class: MJNDatasetSegment
  meta_fn: metadata.json
  batch_size: 4
  src_sr: 48000
  tgt_sr: 24000
  segment_length: 5
  label_frame_rate: 75
  num_workers: 4